### ISSUE TITLE
Add CLI command to get cluster IP

### ISSUE THREAD

**Issue by rushtehrani** [onepanelio/core#155]
The command will be:

```
opctl app ip
```

Which will execute [this code](https://github.com/onepanelio/cli/blob/master/cmd/apply.go#L231-L246)

We will also need to move `opctl status` to `opctl app status`

**Comment by rushtehrani** [comment]
@aleksandrmelnikov getting this error when running the IP command:
```
$ go run main.go app ip
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x4f51d0f]

goroutine 1 [running]:
github.com/onepanelio/cli/util.GetDeployedWebURL(0xc0001321a8, 0xb, 0xc0001321a8, 0x0, 0x0)
        /Users/rush/code/go/src/github.com/onepanelio/cli/util/url.go:20 +0x6f
github.com/onepanelio/cli/cmd.glob..func2(0x61ef080, 0x622ff68, 0x0, 0x0)
        /Users/rush/code/go/src/github.com/onepanelio/cli/cmd/app.go:36 +0x95
github.com/spf13/cobra.(*Command).execute(0x61ef080, 0x622ff68, 0x0, 0x0, 0x61ef080, 0x622ff68)
        /Users/rush/code/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:830 +0x29d
github.com/spf13/cobra.(*Command).ExecuteC(0x61f0200, 0x40447ba, 0x602c620, 0xc000000180)
        /Users/rush/code/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:914 +0x2fb
github.com/spf13/cobra.(*Command).Execute(...)
        /Users/rush/code/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:864
github.com/onepanelio/cli/cmd.Execute()
        /Users/rush/code/go/src/github.com/onepanelio/cli/cmd/root.go:33 +0x31
main.main()
        /Users/rush/code/go/src/github.com/onepanelio/cli/main.go:23 +0x20
exit status 2
```

**Comment by aleksandrmelnikov** [comment]
Was this with azure?
