### ISSUE TITLE
CVAT: Annotation upload error

### ISSUE THREAD

**Issue by rushtehrani** [onepanelio/core#769]
**Describe the bug**
Uploading annotations throws the following error:

```bash
2020-12-06T04:14:58.120892606Z Traceback (most recent call last):
2020-12-06T04:14:58.120903906Z   File "/usr/local/lib/python3.5/dist-packages/rq/worker.py", line 812, in perform_job
2020-12-06T04:14:58.120910107Z     rv = job.perform()
2020-12-06T04:14:58.120914907Z   File "/usr/local/lib/python3.5/dist-packages/rq/job.py", line 588, in perform
2020-12-06T04:14:58.120920007Z     self._result = self._execute()
2020-12-06T04:14:58.120924707Z   File "/usr/local/lib/python3.5/dist-packages/rq/job.py", line 594, in _execute
2020-12-06T04:14:58.120929907Z     return self.func(*self.args, **self.kwargs)
2020-12-06T04:14:58.120935007Z   File "/usr/lib/python3.5/contextlib.py", line 30, in inner
2020-12-06T04:14:58.120940107Z     return func(*args, **kwds)
2020-12-06T04:14:58.120944707Z   File "/home/django/cvat/apps/engine/annotation.py", line 111, in load_task_data
2020-12-06T04:14:58.120949607Z     annotation.upload(filename, loader)
2020-12-06T04:14:58.120960507Z   File "/home/django/cvat/apps/engine/annotation.py", line 766, in upload
2020-12-06T04:14:58.120966807Z     execute_python_code("{}(file_object, annotations)".format(loader.handler), global_vars)
2020-12-06T04:14:58.120974007Z   File "/home/django/cvat/apps/engine/utils.py", line 60, in execute_python_code
2020-12-06T04:14:58.120979907Z     raise InterpreterError("{} at line {}: {}".format(error_class, line_number, details))
2020-12-06T04:14:58.120985207Z cvat.apps.engine.utils.InterpreterError: KeyError at line 226: None
```

**`opctl` version**
```bash
$ opctl version

CLI version: v0.16.0-rc.0
Manifest version: v0.16.0-rc.0
API version: v0.16.0-rc.0
Web UI version: v0.16.0-rc.0
```

**`opctl init` command**
`opctl init --provider gke --artifact-repository-provider s3 --gpu-device-plugins nvidia`

**Kubernetes information**
 - Cloud provider: GKE
 - Kubernetes version: 1.17.13

**Machine information**
- OS: macOS 10.14.6
- Browser: Chrome

**Screenshots**
![image](https://user-images.githubusercontent.com/1211823/101271378-f8fca280-3736-11eb-8e32-d5cf1516d956.png)

**Comment by rushtehrani** [comment]
This was due to label mismatch (data issue)
